### PR TITLE
Chef Infra Client 15.6.10 builds

### PR DESCRIPTION
**Pull request by mattray**

### CODE REVIEW

**Comment by trinitronx** [comment]
@mattray  Quick question:  Can this be made `knife bootstrap`-able?

I've been using [dayne/raspbian_bootstrap][1] for the time being, as it seems to be the most "official" way the community has shared for doing this.  I believe that repo's "[`ruby-omnibus-prebuilt.sh`][2]" script is currently using `chef_14.8.10+20181204005213-1_armhf.deb`.

However, it'd be nice to update to Chef 15 and use this package 😄 

[1]: https://github.com/dayne/raspbian_bootstrap
[2]: https://github.com/dayne/raspbian_bootstrap/blob/master/ruby-omnibus-prebuilt.sh

**Comment by mattray** [comment]
I'm trying to get Chef to support 32-bit ARM with Chef 16, there's definitely customers and users on it. 

I wonder if "knife bootstrap --bootstrap-preinstall-command" could be used to install the artifact and then the bootstrap script would skip ahead because the package is already installed? I haven't tested that.

**Comment by trinitronx** [comment]
Yeah, that might work, although I haven't tried using that `--bootstrap-preinstall-command` flag.   I also have been [using that repo as a submodule][1], so it's easy enough to change the submodule to point at a fork and update the script within to point at your `.deb` file.

[1]: https://github.com/trinitronx/lyraphase-chef/tree/master/chef/bootstrap

**Comment by trinitronx** [comment]
So it looks like it does work after a [couple fixes][1].

Notes:

- I had to use `knife` from `chefdk: 4.7.73`, due to getting an error when using `knife` from bundled gems.
  - Not sure why this happened, but the error was: `sudo: no tty present and no askpass program specified`.
  - I tried adding `Defaults:pi !requiretty`, and `pi         ALL=(ALL:ALL) NOPASSWD:ALL` to the Raspberry Pi's `/etc/sudoers`, but the error persisted.
  - Switching to `knife` from ChefDK package on MacOS fixed the issue 🤷‍♂ 
- `ssh.service` was not started by default on the latest Raspbian image.  Just needed to set up `~/.ssh/authorized_keys` and run: `sudo systemctl start ssh.service`.
- I changed hostname of the Raspberry Pi before provisioning with `sudo hostnamectl my-hostname`, also manually adding it to `/etc/hosts` and `/etc/hostname` to make sure they all matched.
- Finally, the bootstrap command was:  `cd bootstrap/raspbian_bootstrap/ &&  /opt/chefdk/bin/knife bootstrap -t raspbian_bootstrap.erb --connection-user pi --ssh-identity-file ~/.ssh/id_rsa --sudo --ssh-verify-host-key accept_new --host my-hostname.local`

After this bit of setup, the first `chef-client` run worked!  Of course, that includes all the unmentioned, but necessary `~/.chef/knife.rb`, `~/.chef/encrypted_data_bag_secret`, `validation_key`, and other pieces.

[1]: https://github.com/trinitronx/raspbian_bootstrap/tree/testing-mattray-chef-15.8.23

**Pull request merged**
